# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Site Domain')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': "Domain's",
                'abstract': False,
            },
        ),
    ]
